name: Delete Gists

on: 
  schedule: 
    - cron: "* 5 * * *"
  
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
      
      - name: clean gists
      with: 
        python-version: 2.7
      run: |
      python /src/h_snippet/clean_gist.repo.py