name: Delete Gists

on: [push]
  # schedule:
  #   - cron: "* */6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Run cleanup script
      run: python -m ./src/h_snippet/delete_gists.py