# name: Delete Gists

# on:
#   schedule: 
#     - cron: "* * * * *"
  
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 2.7
#       uses: actions/setup-python@v2
#       with:
#         # Semantic version range syntax or exact version of a Python version
#         python-version: '2.7'
#         # Optional - x64 or x86 architecture, defaults to x64
#         architecture: 'x64'
#     # You can test your matrix by printing the current Python version
#     - name: Display Python version
#       with:
#         python-version : 2.7
#       run: python ./src/h_snippet/clean_gist_repo.py
name: Python package

on:
  schedule:
  - cron: "* * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"